module.exports = {
  DEFAULT_LANG: 'en',
  DEV_PORT: process.env.PORT,
  MONGO_CONNECTION_STRING: process.env.MONGO_CONNECTION_STRING,
  SALT_ROUNDS: parseInt(process.env.SALT_ROUNDS),
  TOKEN_EXPIRATION_TIME: process.env.TOKEN_EXPIRATION_TIME,
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  VALIDATION: {
    USER_NAME_MIN_LENGTH: 6,
    USER_EMAIL_MIN_LENGTH: 6,
    USER_EMAIL_MAX_LENGTH: 255,
    USER_PASSWORD_MAX_LENGTH: 1024,
    USER_PASSWORD_MIN_LENGTH: 6,
    REFRESH_TOKEN_MIN_LENGTH: 6,
  },
  CLOUDINARY: {
    CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
    CLOUDINARY_URL: process.env.CLOUDINARY_URL,
  },
};